site_name: Watchtower
site_url: https://nicholas-fedor.github.io/watchtower/
repo_url: https://github.com/nicholas-fedor/watchtower/
edit_uri: edit/main/docs/
theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: watchtower
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: watchtower-dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: images/logo-450px.png
  favicon: images/favicon.ico
extra_css:
  - stylesheets/theme.css
markdown_extensions:
  - toc:
      permalink: True
      separator: "_"
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.magiclink:
      repo_url_shortener: True
      provider: github
      user: nicholas-fedor
      repo: watchtower
  - pymdownx.saneheaders
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - "Home": "index.md"
  - "Getting Started":
      - "Introduction": "introduction.md"
      - "Usage Overview": "usage-overview.md"
  - "Configuration":
      - "Arguments": "arguments.md"
      - "Container Selection": "container-selection.md"
      - "Private Registries": "private-registries.md"
      - "Secure Connections": "secure-connections.md"
  - "Monitoring & Integration":
      - "Notifications": "notifications.md"
      - "Metrics": "metrics.md"
  - "Advanced Features":
      - "Linked Containers": "linked-containers.md"
      - "Remote Hosts": "remote-hosts.md"
      - "Stop Signals": "stop-signals.md"
      - "Lifecycle Hooks": "lifecycle-hooks.md"
      - "Running Multiple Instances": "running-multiple-instances.md"
      - "HTTP API Mode": "http-api-mode.md"
plugins:
  - search
