// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/watchtower/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetLatestCommit provides a mock function for the type MockClient
func (_mock *MockClient) GetLatestCommit(ctx context.Context, repoURL string, ref string, auth types.AuthConfig) (string, error) {
	ret := _mock.Called(ctx, repoURL, ref, auth)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestCommit")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, types.AuthConfig) (string, error)); ok {
		return returnFunc(ctx, repoURL, ref, auth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, types.AuthConfig) string); ok {
		r0 = returnFunc(ctx, repoURL, ref, auth)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, types.AuthConfig) error); ok {
		r1 = returnFunc(ctx, repoURL, ref, auth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetLatestCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestCommit'
type MockClient_GetLatestCommit_Call struct {
	*mock.Call
}

// GetLatestCommit is a helper method to define mock.On call
//   - ctx context.Context
//   - repoURL string
//   - ref string
//   - auth types.AuthConfig
func (_e *MockClient_Expecter) GetLatestCommit(ctx interface{}, repoURL interface{}, ref interface{}, auth interface{}) *MockClient_GetLatestCommit_Call {
	return &MockClient_GetLatestCommit_Call{Call: _e.mock.On("GetLatestCommit", ctx, repoURL, ref, auth)}
}

func (_c *MockClient_GetLatestCommit_Call) Run(run func(ctx context.Context, repoURL string, ref string, auth types.AuthConfig)) *MockClient_GetLatestCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 types.AuthConfig
		if args[3] != nil {
			arg3 = args[3].(types.AuthConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetLatestCommit_Call) Return(s string, err error) *MockClient_GetLatestCommit_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_GetLatestCommit_Call) RunAndReturn(run func(ctx context.Context, repoURL string, ref string, auth types.AuthConfig) (string, error)) *MockClient_GetLatestCommit_Call {
	_c.Call.Return(run)
	return _c
}

// ListBranches provides a mock function for the type MockClient
func (_mock *MockClient) ListBranches(ctx context.Context, repoURL string, auth types.AuthConfig) ([]string, error) {
	ret := _mock.Called(ctx, repoURL, auth)

	if len(ret) == 0 {
		panic("no return value specified for ListBranches")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.AuthConfig) ([]string, error)); ok {
		return returnFunc(ctx, repoURL, auth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.AuthConfig) []string); ok {
		r0 = returnFunc(ctx, repoURL, auth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.AuthConfig) error); ok {
		r1 = returnFunc(ctx, repoURL, auth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListBranches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBranches'
type MockClient_ListBranches_Call struct {
	*mock.Call
}

// ListBranches is a helper method to define mock.On call
//   - ctx context.Context
//   - repoURL string
//   - auth types.AuthConfig
func (_e *MockClient_Expecter) ListBranches(ctx interface{}, repoURL interface{}, auth interface{}) *MockClient_ListBranches_Call {
	return &MockClient_ListBranches_Call{Call: _e.mock.On("ListBranches", ctx, repoURL, auth)}
}

func (_c *MockClient_ListBranches_Call) Run(run func(ctx context.Context, repoURL string, auth types.AuthConfig)) *MockClient_ListBranches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.AuthConfig
		if args[2] != nil {
			arg2 = args[2].(types.AuthConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ListBranches_Call) Return(strings []string, err error) *MockClient_ListBranches_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockClient_ListBranches_Call) RunAndReturn(run func(ctx context.Context, repoURL string, auth types.AuthConfig) ([]string, error)) *MockClient_ListBranches_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function for the type MockClient
func (_mock *MockClient) ListTags(ctx context.Context, repoURL string, auth types.AuthConfig) ([]string, error) {
	ret := _mock.Called(ctx, repoURL, auth)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.AuthConfig) ([]string, error)); ok {
		return returnFunc(ctx, repoURL, auth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.AuthConfig) []string); ok {
		r0 = returnFunc(ctx, repoURL, auth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.AuthConfig) error); ok {
		r1 = returnFunc(ctx, repoURL, auth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type MockClient_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - ctx context.Context
//   - repoURL string
//   - auth types.AuthConfig
func (_e *MockClient_Expecter) ListTags(ctx interface{}, repoURL interface{}, auth interface{}) *MockClient_ListTags_Call {
	return &MockClient_ListTags_Call{Call: _e.mock.On("ListTags", ctx, repoURL, auth)}
}

func (_c *MockClient_ListTags_Call) Run(run func(ctx context.Context, repoURL string, auth types.AuthConfig)) *MockClient_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.AuthConfig
		if args[2] != nil {
			arg2 = args[2].(types.AuthConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ListTags_Call) Return(strings []string, err error) *MockClient_ListTags_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockClient_ListTags_Call) RunAndReturn(run func(ctx context.Context, repoURL string, auth types.AuthConfig) ([]string, error)) *MockClient_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRepository provides a mock function for the type MockClient
func (_mock *MockClient) ValidateRepository(ctx context.Context, repoURL string, auth types.AuthConfig) error {
	ret := _mock.Called(ctx, repoURL, auth)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.AuthConfig) error); ok {
		r0 = returnFunc(ctx, repoURL, auth)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ValidateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRepository'
type MockClient_ValidateRepository_Call struct {
	*mock.Call
}

// ValidateRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - repoURL string
//   - auth types.AuthConfig
func (_e *MockClient_Expecter) ValidateRepository(ctx interface{}, repoURL interface{}, auth interface{}) *MockClient_ValidateRepository_Call {
	return &MockClient_ValidateRepository_Call{Call: _e.mock.On("ValidateRepository", ctx, repoURL, auth)}
}

func (_c *MockClient_ValidateRepository_Call) Run(run func(ctx context.Context, repoURL string, auth types.AuthConfig)) *MockClient_ValidateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.AuthConfig
		if args[2] != nil {
			arg2 = args[2].(types.AuthConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ValidateRepository_Call) Return(err error) *MockClient_ValidateRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ValidateRepository_Call) RunAndReturn(run func(ctx context.Context, repoURL string, auth types.AuthConfig) error) *MockClient_ValidateRepository_Call {
	_c.Call.Return(run)
	return _c
}
