// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/watchtower/pkg/types"
	"github.com/sirupsen/logrus"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// AddLogHook provides a mock function for the type MockNotifier
func (_mock *MockNotifier) AddLogHook() {
	_mock.Called()
	return
}

// MockNotifier_AddLogHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLogHook'
type MockNotifier_AddLogHook_Call struct {
	*mock.Call
}

// AddLogHook is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) AddLogHook() *MockNotifier_AddLogHook_Call {
	return &MockNotifier_AddLogHook_Call{Call: _e.mock.On("AddLogHook")}
}

func (_c *MockNotifier_AddLogHook_Call) Run(run func()) *MockNotifier_AddLogHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_AddLogHook_Call) Return() *MockNotifier_AddLogHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_AddLogHook_Call) RunAndReturn(run func()) *MockNotifier_AddLogHook_Call {
	_c.Run(run)
	return _c
}

// Close provides a mock function for the type MockNotifier
func (_mock *MockNotifier) Close() {
	_mock.Called()
	return
}

// MockNotifier_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockNotifier_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) Close() *MockNotifier_Close_Call {
	return &MockNotifier_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockNotifier_Close_Call) Run(run func()) *MockNotifier_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_Close_Call) Return() *MockNotifier_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_Close_Call) RunAndReturn(run func()) *MockNotifier_Close_Call {
	_c.Run(run)
	return _c
}

// GetEntries provides a mock function for the type MockNotifier
func (_mock *MockNotifier) GetEntries() []*logrus.Entry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEntries")
	}

	var r0 []*logrus.Entry
	if returnFunc, ok := ret.Get(0).(func() []*logrus.Entry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*logrus.Entry)
		}
	}
	return r0
}

// MockNotifier_GetEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntries'
type MockNotifier_GetEntries_Call struct {
	*mock.Call
}

// GetEntries is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) GetEntries() *MockNotifier_GetEntries_Call {
	return &MockNotifier_GetEntries_Call{Call: _e.mock.On("GetEntries")}
}

func (_c *MockNotifier_GetEntries_Call) Run(run func()) *MockNotifier_GetEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_GetEntries_Call) Return(entrys []*logrus.Entry) *MockNotifier_GetEntries_Call {
	_c.Call.Return(entrys)
	return _c
}

func (_c *MockNotifier_GetEntries_Call) RunAndReturn(run func() []*logrus.Entry) *MockNotifier_GetEntries_Call {
	_c.Call.Return(run)
	return _c
}

// GetNames provides a mock function for the type MockNotifier
func (_mock *MockNotifier) GetNames() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNames")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockNotifier_GetNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNames'
type MockNotifier_GetNames_Call struct {
	*mock.Call
}

// GetNames is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) GetNames() *MockNotifier_GetNames_Call {
	return &MockNotifier_GetNames_Call{Call: _e.mock.On("GetNames")}
}

func (_c *MockNotifier_GetNames_Call) Run(run func()) *MockNotifier_GetNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_GetNames_Call) Return(strings []string) *MockNotifier_GetNames_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockNotifier_GetNames_Call) RunAndReturn(run func() []string) *MockNotifier_GetNames_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLs provides a mock function for the type MockNotifier
func (_mock *MockNotifier) GetURLs() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetURLs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockNotifier_GetURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLs'
type MockNotifier_GetURLs_Call struct {
	*mock.Call
}

// GetURLs is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) GetURLs() *MockNotifier_GetURLs_Call {
	return &MockNotifier_GetURLs_Call{Call: _e.mock.On("GetURLs")}
}

func (_c *MockNotifier_GetURLs_Call) Run(run func()) *MockNotifier_GetURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_GetURLs_Call) Return(strings []string) *MockNotifier_GetURLs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockNotifier_GetURLs_Call) RunAndReturn(run func() []string) *MockNotifier_GetURLs_Call {
	_c.Call.Return(run)
	return _c
}

// SendFilteredEntries provides a mock function for the type MockNotifier
func (_mock *MockNotifier) SendFilteredEntries(entries []*logrus.Entry, report types.Report) {
	_mock.Called(entries, report)
	return
}

// MockNotifier_SendFilteredEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendFilteredEntries'
type MockNotifier_SendFilteredEntries_Call struct {
	*mock.Call
}

// SendFilteredEntries is a helper method to define mock.On call
//   - entries []*logrus.Entry
//   - report types.Report
func (_e *MockNotifier_Expecter) SendFilteredEntries(entries interface{}, report interface{}) *MockNotifier_SendFilteredEntries_Call {
	return &MockNotifier_SendFilteredEntries_Call{Call: _e.mock.On("SendFilteredEntries", entries, report)}
}

func (_c *MockNotifier_SendFilteredEntries_Call) Run(run func(entries []*logrus.Entry, report types.Report)) *MockNotifier_SendFilteredEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*logrus.Entry
		if args[0] != nil {
			arg0 = args[0].([]*logrus.Entry)
		}
		var arg1 types.Report
		if args[1] != nil {
			arg1 = args[1].(types.Report)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifier_SendFilteredEntries_Call) Return() *MockNotifier_SendFilteredEntries_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_SendFilteredEntries_Call) RunAndReturn(run func(entries []*logrus.Entry, report types.Report)) *MockNotifier_SendFilteredEntries_Call {
	_c.Run(run)
	return _c
}

// SendNotification provides a mock function for the type MockNotifier
func (_mock *MockNotifier) SendNotification(reportType types.Report) {
	_mock.Called(reportType)
	return
}

// MockNotifier_SendNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendNotification'
type MockNotifier_SendNotification_Call struct {
	*mock.Call
}

// SendNotification is a helper method to define mock.On call
//   - reportType types.Report
func (_e *MockNotifier_Expecter) SendNotification(reportType interface{}) *MockNotifier_SendNotification_Call {
	return &MockNotifier_SendNotification_Call{Call: _e.mock.On("SendNotification", reportType)}
}

func (_c *MockNotifier_SendNotification_Call) Run(run func(reportType types.Report)) *MockNotifier_SendNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Report
		if args[0] != nil {
			arg0 = args[0].(types.Report)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotifier_SendNotification_Call) Return() *MockNotifier_SendNotification_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_SendNotification_Call) RunAndReturn(run func(reportType types.Report)) *MockNotifier_SendNotification_Call {
	_c.Run(run)
	return _c
}

// StartNotification provides a mock function for the type MockNotifier
func (_mock *MockNotifier) StartNotification() {
	_mock.Called()
	return
}

// MockNotifier_StartNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartNotification'
type MockNotifier_StartNotification_Call struct {
	*mock.Call
}

// StartNotification is a helper method to define mock.On call
func (_e *MockNotifier_Expecter) StartNotification() *MockNotifier_StartNotification_Call {
	return &MockNotifier_StartNotification_Call{Call: _e.mock.On("StartNotification")}
}

func (_c *MockNotifier_StartNotification_Call) Run(run func()) *MockNotifier_StartNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotifier_StartNotification_Call) Return() *MockNotifier_StartNotification_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_StartNotification_Call) RunAndReturn(run func()) *MockNotifier_StartNotification_Call {
	_c.Run(run)
	return _c
}
