// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPServer is an autogenerated mock type for the HTTPServer type
type MockHTTPServer struct {
	mock.Mock
}

type MockHTTPServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPServer) EXPECT() *MockHTTPServer_Expecter {
	return &MockHTTPServer_Expecter{mock: &_m.Mock}
}

// ListenAndServe provides a mock function with no fields
func (_m *MockHTTPServer) ListenAndServe() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListenAndServe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHTTPServer_ListenAndServe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenAndServe'
type MockHTTPServer_ListenAndServe_Call struct {
	*mock.Call
}

// ListenAndServe is a helper method to define mock.On call
func (_e *MockHTTPServer_Expecter) ListenAndServe() *MockHTTPServer_ListenAndServe_Call {
	return &MockHTTPServer_ListenAndServe_Call{Call: _e.mock.On("ListenAndServe")}
}

func (_c *MockHTTPServer_ListenAndServe_Call) Run(run func()) *MockHTTPServer_ListenAndServe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHTTPServer_ListenAndServe_Call) Return(_a0 error) *MockHTTPServer_ListenAndServe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPServer_ListenAndServe_Call) RunAndReturn(run func() error) *MockHTTPServer_ListenAndServe_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockHTTPServer) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHTTPServer_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockHTTPServer_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHTTPServer_Expecter) Shutdown(ctx interface{}) *MockHTTPServer_Shutdown_Call {
	return &MockHTTPServer_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockHTTPServer_Shutdown_Call) Run(run func(ctx context.Context)) *MockHTTPServer_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHTTPServer_Shutdown_Call) Return(_a0 error) *MockHTTPServer_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPServer_Shutdown_Call) RunAndReturn(run func(context.Context) error) *MockHTTPServer_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPServer creates a new instance of MockHTTPServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPServer {
	mock := &MockHTTPServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
