# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Enable dynamic config for path-based filtering.
setup: true

# Orbs for reusable packages.
orbs:
  path-filtering: circleci/path-filtering@2.0.4

# Orchestrate jobs using workflows.
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  setup-workflow: # This workflow checks changed files and decides whether to continue.
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: | # Map file patterns to pipeline parameters (true/false).
            cmd/.* run-tests true
            internal/.* run-tests true
            pkg/.* run-tests true
            main.go run-tests true
            go.mod run-tests true
            go.sum run-tests true
          base-revision: main # Compare against the base branch.
          config-path: .circleci/continue-config.yml # Path to the continuation config if conditions match.
