// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/watchtower/internal/git"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRefLister creates a new instance of MockRefLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRefLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRefLister is an autogenerated mock type for the RefLister type
type MockRefLister struct {
	mock.Mock
}

type MockRefLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefLister) EXPECT() *MockRefLister_Expecter {
	return &MockRefLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockRefLister
func (_mock *MockRefLister) List(ctx context.Context, repo string) ([]git.RemoteRef, error) {
	ret := _mock.Called(ctx, repo)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []git.RemoteRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]git.RemoteRef, error)); ok {
		return returnFunc(ctx, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []git.RemoteRef); ok {
		r0 = returnFunc(ctx, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]git.RemoteRef)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRefLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
func (_e *MockRefLister_Expecter) List(ctx any, repo any) *MockRefLister_List_Call {
	return &MockRefLister_List_Call{Call: _e.mock.On("List", ctx, repo)}
}

func (_c *MockRefLister_List_Call) Run(run func(ctx context.Context, repo string)) *MockRefLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefLister_List_Call) Return(remoteRefs []git.RemoteRef, err error) *MockRefLister_List_Call {
	_c.Call.Return(remoteRefs, err)
	return _c
}

func (_c *MockRefLister_List_Call) RunAndReturn(run func(ctx context.Context, repo string) ([]git.RemoteRef, error)) *MockRefLister_List_Call {
	_c.Call.Return(run)
	return _c
}
