name: 🐛 Bug report
description: Report a bug or issue with Watchtower.
title: "[Bug]:"
labels: ["Type: Bug"]

body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for reporting a bug!

        - Check [existing issues](https://github.com/nicholas-fedor/watchtower/issues) to avoid duplicates!
        - For support, [start a discussion](https://github.com/nicholas-fedor/watchtower/discussions/new?category=support).
        - For features, use the [feature request form](https://github.com/nicholas-fedor/watchtower/issues/new?template=feature_request.yml).
        - If you have additional items to share, such as debug log files or screenshots, then you may attach them in subsequent messages.

        [!WARNING] Do NOT submit sensitive information in logs, screenshots, etc that could lead to system/account compromise.

  - type: checkboxes
    id: checklist
    attributes:
      label: Bug Report Checklist
      options:
        - label: I checked [existing issues](https://github.com/nicholas-fedor/watchtower/issues) and found no duplicates.
          required: true
        - label: I have reviewed Watchtower's [documentation](https://watchtower.nickfedor.com/latest/) and confirmed compliance with documented configuration specifications.
          required: true
        - label: I have restarted Docker, re-pulled the `latest` image, and confirmed that the issue persists.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the issue clearly and concisely.
      placeholder: e.g., Watchtower fails to update containers with scoped registries.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue.
      placeholder: |
        1. Start Watchtower with Docker compose: `docker compose up -d`
        2. Wait for the update cycle
        3. Observe the errant behavior in Docker logs or notifications
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: e.g., Watchtower should update all eligible containers without errors.
    validations:
      required: true

  - type: input
    id: watchtower_version
    attributes:
      label: Watchtower Version
      description: Which version of Watchtower are you using?
      placeholder: e.g., latest, v1.14.0, or commit hash
    validations:
      required: true

  - type: textarea
    id: docker_version
    attributes:
      label: Docker Version
      description: Output of `docker version`
      render: bash
    validations:
      required: true

  - type: textarea
    id: docker_info
    attributes:
      label: Docker Info
      description: Output of `docker info` (optional)
      render: bash
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Watchtower Configuration
      description: |
        How are you running Watchtower?
        Please provide your Docker command, docker-compose.yml, or other configuration details.
      placeholder: |
        e.g., Docker command:
        ```bash
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          nickfedor/watchtower:latest \
          --debug \
          --interval 30 \
          --cleanup
        ```

        Or docker-compose.yml:
        ```yaml
        services:
          watchtower:
            image: nickfedor/watchtower:latest
            restart: unless-stopped
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
        ```
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Debug Logs
      description: |
        Paste the logs from running Watchtower with the `--debug` or `WATCHTOWER_DEBUG=true` option.
        If you need to submit full debug logs, then you should add them as an attachment in a separate message after submitting the issue.

        Info-level logs are typically not sufficient for debugging issues!
      render: text
      placeholder: |
        Example log output:
        ```
        time="2023-01-01T00:00:00Z" level=debug msg="Checking for updates..."
        time="2023-01-01T00:00:00Z" level=error msg="Failed to check for updates: ..."
        ```
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
      Add any other context about the problem here, such as related issues, workarounds you've tried, or specific container images affected.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Before you submit:
          - You are expected to perform your own due diligence prior to submitting issues for review.
          - Please double-check that you have provided sufficient information to allow for replication and debugging of the issue!
          - Issues that are duplicates, configuration issues, and/or fail to provide sufficient information are subject to immediate closure.
