name: 💡 Feature request
description: Suggest a new feature or enhancement for Watchtower.
labels: ["Type: Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for suggesting a new feature!

        Before submitting, please:
        - Search [existing issues](https://github.com/nicholas-fedor/watchtower/issues) and [discussions](https://github.com/nicholas-fedor/watchtower/discussions).
        - For support, use [Discussions](https://github.com/nicholas-fedor/watchtower/discussions).
        - See [Contributing](https://github.com/nicholas-fedor/watchtower?tab=contributing-ov-file) for guidelines.

  - type: checkboxes
    id: checklist
    attributes:
      label: Feature Request Checklist
      options:
        - label: I checked [existing issues](https://github.com/nicholas-fedor/watchtower/issues) and [discussions](https://github.com/nicholas-fedor/watchtower/discussions) for duplicates.
          required: true
        - label: This is a feature request, not a support question.
          required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: A clear and concise description of what the problem.
      placeholder: e.g., Watchtower currently does not support X.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Desired Solution
      description: A clear and concise description of what you want to happen.
      placeholder: e.g., Watchtower to support X by implementing functionality according to Y standard.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Current Alternatives or Workarounds
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: e.g., Using a lifecycle script that runs after the container has been updated.
    validations:
      required: true

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
