// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/moby/moby/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockArchiveAPI creates a new instance of MockArchiveAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArchiveAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArchiveAPI {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockArchiveAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockArchiveAPI is an autogenerated mock type for the ArchiveAPI type
type MockArchiveAPI struct {
	mock.Mock
}

type MockArchiveAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArchiveAPI) EXPECT() *MockArchiveAPI_Expecter {
	return &MockArchiveAPI_Expecter{mock: &_m.Mock}
}

// CopyFromContainer provides a mock function for the type MockArchiveAPI
func (_mock *MockArchiveAPI) CopyFromContainer(ctx context.Context, containerID string, options client.CopyFromContainerOptions) (client.CopyFromContainerResult, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for CopyFromContainer")
	}

	var r0 client.CopyFromContainerResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.CopyFromContainerOptions) (client.CopyFromContainerResult, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.CopyFromContainerOptions) client.CopyFromContainerResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.CopyFromContainerResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.CopyFromContainerOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArchiveAPI_CopyFromContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyFromContainer'
type MockArchiveAPI_CopyFromContainer_Call struct {
	*mock.Call
}

// CopyFromContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.CopyFromContainerOptions
func (_e *MockArchiveAPI_Expecter) CopyFromContainer(ctx any, containerID any, options any) *MockArchiveAPI_CopyFromContainer_Call {
	return &MockArchiveAPI_CopyFromContainer_Call{Call: _e.mock.On("CopyFromContainer", ctx, containerID, options)}
}

func (_c *MockArchiveAPI_CopyFromContainer_Call) Run(run func(ctx context.Context, containerID string, options client.CopyFromContainerOptions)) *MockArchiveAPI_CopyFromContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.CopyFromContainerOptions
		if args[2] != nil {
			arg2 = args[2].(client.CopyFromContainerOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockArchiveAPI_CopyFromContainer_Call) Return(copyFromContainerResult client.CopyFromContainerResult, err error) *MockArchiveAPI_CopyFromContainer_Call {
	_c.Call.Return(copyFromContainerResult, err)
	return _c
}

func (_c *MockArchiveAPI_CopyFromContainer_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.CopyFromContainerOptions) (client.CopyFromContainerResult, error)) *MockArchiveAPI_CopyFromContainer_Call {
	_c.Call.Return(run)
	return _c
}

// CopyToContainer provides a mock function for the type MockArchiveAPI
func (_mock *MockArchiveAPI) CopyToContainer(ctx context.Context, containerID string, options client.CopyToContainerOptions) (client.CopyToContainerResult, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for CopyToContainer")
	}

	var r0 client.CopyToContainerResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.CopyToContainerOptions) (client.CopyToContainerResult, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.CopyToContainerOptions) client.CopyToContainerResult); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Get(0).(client.CopyToContainerResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.CopyToContainerOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArchiveAPI_CopyToContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyToContainer'
type MockArchiveAPI_CopyToContainer_Call struct {
	*mock.Call
}

// CopyToContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options client.CopyToContainerOptions
func (_e *MockArchiveAPI_Expecter) CopyToContainer(ctx any, containerID any, options any) *MockArchiveAPI_CopyToContainer_Call {
	return &MockArchiveAPI_CopyToContainer_Call{Call: _e.mock.On("CopyToContainer", ctx, containerID, options)}
}

func (_c *MockArchiveAPI_CopyToContainer_Call) Run(run func(ctx context.Context, containerID string, options client.CopyToContainerOptions)) *MockArchiveAPI_CopyToContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.CopyToContainerOptions
		if args[2] != nil {
			arg2 = args[2].(client.CopyToContainerOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockArchiveAPI_CopyToContainer_Call) Return(copyToContainerResult client.CopyToContainerResult, err error) *MockArchiveAPI_CopyToContainer_Call {
	_c.Call.Return(copyToContainerResult, err)
	return _c
}

func (_c *MockArchiveAPI_CopyToContainer_Call) RunAndReturn(run func(ctx context.Context, containerID string, options client.CopyToContainerOptions) (client.CopyToContainerResult, error)) *MockArchiveAPI_CopyToContainer_Call {
	_c.Call.Return(run)
	return _c
}
