// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	types "github.com/nicholas-fedor/watchtower/pkg/types"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// ExecuteCommand provides a mock function with given fields: containerID, command, timeout
func (_m *MockClient) ExecuteCommand(containerID types.ContainerID, command string, timeout int) (bool, error) {
	ret := _m.Called(containerID, command, timeout)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteCommand")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(types.ContainerID, string, int) (bool, error)); ok {
		return rf(containerID, command, timeout)
	}
	if rf, ok := ret.Get(0).(func(types.ContainerID, string, int) bool); ok {
		r0 = rf(containerID, command, timeout)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(types.ContainerID, string, int) error); ok {
		r1 = rf(containerID, command, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ExecuteCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteCommand'
type MockClient_ExecuteCommand_Call struct {
	*mock.Call
}

// ExecuteCommand is a helper method to define mock.On call
//   - containerID types.ContainerID
//   - command string
//   - timeout int
func (_e *MockClient_Expecter) ExecuteCommand(containerID interface{}, command interface{}, timeout interface{}) *MockClient_ExecuteCommand_Call {
	return &MockClient_ExecuteCommand_Call{Call: _e.mock.On("ExecuteCommand", containerID, command, timeout)}
}

func (_c *MockClient_ExecuteCommand_Call) Run(run func(containerID types.ContainerID, command string, timeout int)) *MockClient_ExecuteCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.ContainerID), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockClient_ExecuteCommand_Call) Return(_a0 bool, _a1 error) *MockClient_ExecuteCommand_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ExecuteCommand_Call) RunAndReturn(run func(types.ContainerID, string, int) (bool, error)) *MockClient_ExecuteCommand_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainer provides a mock function with given fields: containerID
func (_m *MockClient) GetContainer(containerID types.ContainerID) (types.Container, error) {
	ret := _m.Called(containerID)

	if len(ret) == 0 {
		panic("no return value specified for GetContainer")
	}

	var r0 types.Container
	var r1 error
	if rf, ok := ret.Get(0).(func(types.ContainerID) (types.Container, error)); ok {
		return rf(containerID)
	}
	if rf, ok := ret.Get(0).(func(types.ContainerID) types.Container); ok {
		r0 = rf(containerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Container)
		}
	}

	if rf, ok := ret.Get(1).(func(types.ContainerID) error); ok {
		r1 = rf(containerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainer'
type MockClient_GetContainer_Call struct {
	*mock.Call
}

// GetContainer is a helper method to define mock.On call
//   - containerID types.ContainerID
func (_e *MockClient_Expecter) GetContainer(containerID interface{}) *MockClient_GetContainer_Call {
	return &MockClient_GetContainer_Call{Call: _e.mock.On("GetContainer", containerID)}
}

func (_c *MockClient_GetContainer_Call) Run(run func(containerID types.ContainerID)) *MockClient_GetContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.ContainerID))
	})
	return _c
}

func (_c *MockClient_GetContainer_Call) Return(_a0 types.Container, _a1 error) *MockClient_GetContainer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetContainer_Call) RunAndReturn(run func(types.ContainerID) (types.Container, error)) *MockClient_GetContainer_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with no fields
func (_m *MockClient) GetVersion() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockClient_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockClient_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
func (_e *MockClient_Expecter) GetVersion() *MockClient_GetVersion_Call {
	return &MockClient_GetVersion_Call{Call: _e.mock.On("GetVersion")}
}

func (_c *MockClient_GetVersion_Call) Run(run func()) *MockClient_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_GetVersion_Call) Return(_a0 string) *MockClient_GetVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_GetVersion_Call) RunAndReturn(run func() string) *MockClient_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// IsContainerStale provides a mock function with given fields: _a0, params
func (_m *MockClient) IsContainerStale(_a0 types.Container, params types.UpdateParams) (bool, types.ImageID, error) {
	ret := _m.Called(_a0, params)

	if len(ret) == 0 {
		panic("no return value specified for IsContainerStale")
	}

	var r0 bool
	var r1 types.ImageID
	var r2 error
	if rf, ok := ret.Get(0).(func(types.Container, types.UpdateParams) (bool, types.ImageID, error)); ok {
		return rf(_a0, params)
	}
	if rf, ok := ret.Get(0).(func(types.Container, types.UpdateParams) bool); ok {
		r0 = rf(_a0, params)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(types.Container, types.UpdateParams) types.ImageID); ok {
		r1 = rf(_a0, params)
	} else {
		r1 = ret.Get(1).(types.ImageID)
	}

	if rf, ok := ret.Get(2).(func(types.Container, types.UpdateParams) error); ok {
		r2 = rf(_a0, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_IsContainerStale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsContainerStale'
type MockClient_IsContainerStale_Call struct {
	*mock.Call
}

// IsContainerStale is a helper method to define mock.On call
//   - _a0 types.Container
//   - params types.UpdateParams
func (_e *MockClient_Expecter) IsContainerStale(_a0 interface{}, params interface{}) *MockClient_IsContainerStale_Call {
	return &MockClient_IsContainerStale_Call{Call: _e.mock.On("IsContainerStale", _a0, params)}
}

func (_c *MockClient_IsContainerStale_Call) Run(run func(_a0 types.Container, params types.UpdateParams)) *MockClient_IsContainerStale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Container), args[1].(types.UpdateParams))
	})
	return _c
}

func (_c *MockClient_IsContainerStale_Call) Return(_a0 bool, _a1 types.ImageID, _a2 error) *MockClient_IsContainerStale_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_IsContainerStale_Call) RunAndReturn(run func(types.Container, types.UpdateParams) (bool, types.ImageID, error)) *MockClient_IsContainerStale_Call {
	_c.Call.Return(run)
	return _c
}

// ListContainers provides a mock function with given fields: filter
func (_m *MockClient) ListContainers(filter types.Filter) ([]types.Container, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for ListContainers")
	}

	var r0 []types.Container
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Filter) ([]types.Container, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(types.Filter) []types.Container); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Container)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Filter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainers'
type MockClient_ListContainers_Call struct {
	*mock.Call
}

// ListContainers is a helper method to define mock.On call
//   - filter types.Filter
func (_e *MockClient_Expecter) ListContainers(filter interface{}) *MockClient_ListContainers_Call {
	return &MockClient_ListContainers_Call{Call: _e.mock.On("ListContainers", filter)}
}

func (_c *MockClient_ListContainers_Call) Run(run func(filter types.Filter)) *MockClient_ListContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Filter))
	})
	return _c
}

func (_c *MockClient_ListContainers_Call) Return(_a0 []types.Container, _a1 error) *MockClient_ListContainers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListContainers_Call) RunAndReturn(run func(types.Filter) ([]types.Container, error)) *MockClient_ListContainers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveImageByID provides a mock function with given fields: imageID
func (_m *MockClient) RemoveImageByID(imageID types.ImageID) error {
	ret := _m.Called(imageID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveImageByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.ImageID) error); ok {
		r0 = rf(imageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_RemoveImageByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveImageByID'
type MockClient_RemoveImageByID_Call struct {
	*mock.Call
}

// RemoveImageByID is a helper method to define mock.On call
//   - imageID types.ImageID
func (_e *MockClient_Expecter) RemoveImageByID(imageID interface{}) *MockClient_RemoveImageByID_Call {
	return &MockClient_RemoveImageByID_Call{Call: _e.mock.On("RemoveImageByID", imageID)}
}

func (_c *MockClient_RemoveImageByID_Call) Run(run func(imageID types.ImageID)) *MockClient_RemoveImageByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.ImageID))
	})
	return _c
}

func (_c *MockClient_RemoveImageByID_Call) Return(_a0 error) *MockClient_RemoveImageByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_RemoveImageByID_Call) RunAndReturn(run func(types.ImageID) error) *MockClient_RemoveImageByID_Call {
	_c.Call.Return(run)
	return _c
}

// RenameContainer provides a mock function with given fields: _a0, newName
func (_m *MockClient) RenameContainer(_a0 types.Container, newName string) error {
	ret := _m.Called(_a0, newName)

	if len(ret) == 0 {
		panic("no return value specified for RenameContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Container, string) error); ok {
		r0 = rf(_a0, newName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_RenameContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameContainer'
type MockClient_RenameContainer_Call struct {
	*mock.Call
}

// RenameContainer is a helper method to define mock.On call
//   - _a0 types.Container
//   - newName string
func (_e *MockClient_Expecter) RenameContainer(_a0 interface{}, newName interface{}) *MockClient_RenameContainer_Call {
	return &MockClient_RenameContainer_Call{Call: _e.mock.On("RenameContainer", _a0, newName)}
}

func (_c *MockClient_RenameContainer_Call) Run(run func(_a0 types.Container, newName string)) *MockClient_RenameContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Container), args[1].(string))
	})
	return _c
}

func (_c *MockClient_RenameContainer_Call) Return(_a0 error) *MockClient_RenameContainer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_RenameContainer_Call) RunAndReturn(run func(types.Container, string) error) *MockClient_RenameContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StartContainer provides a mock function with given fields: _a0
func (_m *MockClient) StartContainer(_a0 types.Container) (types.ContainerID, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for StartContainer")
	}

	var r0 types.ContainerID
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Container) (types.ContainerID, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(types.Container) types.ContainerID); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.ContainerID)
	}

	if rf, ok := ret.Get(1).(func(types.Container) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_StartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartContainer'
type MockClient_StartContainer_Call struct {
	*mock.Call
}

// StartContainer is a helper method to define mock.On call
//   - _a0 types.Container
func (_e *MockClient_Expecter) StartContainer(_a0 interface{}) *MockClient_StartContainer_Call {
	return &MockClient_StartContainer_Call{Call: _e.mock.On("StartContainer", _a0)}
}

func (_c *MockClient_StartContainer_Call) Run(run func(_a0 types.Container)) *MockClient_StartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Container))
	})
	return _c
}

func (_c *MockClient_StartContainer_Call) Return(_a0 types.ContainerID, _a1 error) *MockClient_StartContainer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_StartContainer_Call) RunAndReturn(run func(types.Container) (types.ContainerID, error)) *MockClient_StartContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopContainer provides a mock function with given fields: _a0, timeout
func (_m *MockClient) StopContainer(_a0 types.Container, timeout time.Duration) error {
	ret := _m.Called(_a0, timeout)

	if len(ret) == 0 {
		panic("no return value specified for StopContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Container, time.Duration) error); ok {
		r0 = rf(_a0, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_StopContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainer'
type MockClient_StopContainer_Call struct {
	*mock.Call
}

// StopContainer is a helper method to define mock.On call
//   - _a0 types.Container
//   - timeout time.Duration
func (_e *MockClient_Expecter) StopContainer(_a0 interface{}, timeout interface{}) *MockClient_StopContainer_Call {
	return &MockClient_StopContainer_Call{Call: _e.mock.On("StopContainer", _a0, timeout)}
}

func (_c *MockClient_StopContainer_Call) Run(run func(_a0 types.Container, timeout time.Duration)) *MockClient_StopContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Container), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockClient_StopContainer_Call) Return(_a0 error) *MockClient_StopContainer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_StopContainer_Call) RunAndReturn(run func(types.Container, time.Duration) error) *MockClient_StopContainer_Call {
	_c.Call.Return(run)
	return _c
}

// WarnOnHeadPullFailed provides a mock function with given fields: _a0
func (_m *MockClient) WarnOnHeadPullFailed(_a0 types.Container) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for WarnOnHeadPullFailed")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(types.Container) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockClient_WarnOnHeadPullFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnOnHeadPullFailed'
type MockClient_WarnOnHeadPullFailed_Call struct {
	*mock.Call
}

// WarnOnHeadPullFailed is a helper method to define mock.On call
//   - _a0 types.Container
func (_e *MockClient_Expecter) WarnOnHeadPullFailed(_a0 interface{}) *MockClient_WarnOnHeadPullFailed_Call {
	return &MockClient_WarnOnHeadPullFailed_Call{Call: _e.mock.On("WarnOnHeadPullFailed", _a0)}
}

func (_c *MockClient_WarnOnHeadPullFailed_Call) Run(run func(_a0 types.Container)) *MockClient_WarnOnHeadPullFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Container))
	})
	return _c
}

func (_c *MockClient_WarnOnHeadPullFailed_Call) Return(_a0 bool) *MockClient_WarnOnHeadPullFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_WarnOnHeadPullFailed_Call) RunAndReturn(run func(types.Container) bool) *MockClient_WarnOnHeadPullFailed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
