// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/watchtower/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCopyFileStore creates a new instance of MockCopyFileStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCopyFileStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCopyFileStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCopyFileStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCopyFileStore is an autogenerated mock type for the CopyFileStore type
type MockCopyFileStore struct {
	mock.Mock
}

type MockCopyFileStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCopyFileStore) EXPECT() *MockCopyFileStore_Expecter {
	return &MockCopyFileStore_Expecter{mock: &_m.Mock}
}

// DiscardCopyFiles provides a mock function for the type MockCopyFileStore
func (_mock *MockCopyFileStore) DiscardCopyFiles(containerID types.ContainerID) {
	_mock.Called(containerID)
	return
}

// MockCopyFileStore_DiscardCopyFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscardCopyFiles'
type MockCopyFileStore_DiscardCopyFiles_Call struct {
	*mock.Call
}

// DiscardCopyFiles is a helper method to define mock.On call
//   - containerID types.ContainerID
func (_e *MockCopyFileStore_Expecter) DiscardCopyFiles(containerID any) *MockCopyFileStore_DiscardCopyFiles_Call {
	return &MockCopyFileStore_DiscardCopyFiles_Call{Call: _e.mock.On("DiscardCopyFiles", containerID)}
}

func (_c *MockCopyFileStore_DiscardCopyFiles_Call) Run(run func(containerID types.ContainerID)) *MockCopyFileStore_DiscardCopyFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.ContainerID
		if args[0] != nil {
			arg0 = args[0].(types.ContainerID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCopyFileStore_DiscardCopyFiles_Call) Return() *MockCopyFileStore_DiscardCopyFiles_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCopyFileStore_DiscardCopyFiles_Call) RunAndReturn(run func(containerID types.ContainerID)) *MockCopyFileStore_DiscardCopyFiles_Call {
	_c.Run(run)
	return _c
}

// SnapshotCopyFiles provides a mock function for the type MockCopyFileStore
func (_mock *MockCopyFileStore) SnapshotCopyFiles(ctx context.Context, container types.Container) error {
	ret := _mock.Called(ctx, container)

	if len(ret) == 0 {
		panic("no return value specified for SnapshotCopyFiles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Container) error); ok {
		r0 = returnFunc(ctx, container)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCopyFileStore_SnapshotCopyFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SnapshotCopyFiles'
type MockCopyFileStore_SnapshotCopyFiles_Call struct {
	*mock.Call
}

// SnapshotCopyFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - container types.Container
func (_e *MockCopyFileStore_Expecter) SnapshotCopyFiles(ctx any, container any) *MockCopyFileStore_SnapshotCopyFiles_Call {
	return &MockCopyFileStore_SnapshotCopyFiles_Call{Call: _e.mock.On("SnapshotCopyFiles", ctx, container)}
}

func (_c *MockCopyFileStore_SnapshotCopyFiles_Call) Run(run func(ctx context.Context, container types.Container)) *MockCopyFileStore_SnapshotCopyFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Container
		if args[1] != nil {
			arg1 = args[1].(types.Container)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCopyFileStore_SnapshotCopyFiles_Call) Return(err error) *MockCopyFileStore_SnapshotCopyFiles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCopyFileStore_SnapshotCopyFiles_Call) RunAndReturn(run func(ctx context.Context, container types.Container) error) *MockCopyFileStore_SnapshotCopyFiles_Call {
	_c.Call.Return(run)
	return _c
}
