// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/watchtower/internal/compose"
	mock "github.com/stretchr/testify/mock"
)

// NewMockApplier creates a new instance of MockApplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplier {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockApplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockApplier is an autogenerated mock type for the Applier type
type MockApplier struct {
	mock.Mock
}

type MockApplier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplier) EXPECT() *MockApplier_Expecter {
	return &MockApplier_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockApplier
func (_mock *MockApplier) Apply(ctx context.Context, req compose.Request) ([]compose.Container, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 []compose.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compose.Request) ([]compose.Container, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compose.Request) []compose.Container); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compose.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compose.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApplier_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockApplier_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - req compose.Request
func (_e *MockApplier_Expecter) Apply(ctx any, req any) *MockApplier_Apply_Call {
	return &MockApplier_Apply_Call{Call: _e.mock.On("Apply", ctx, req)}
}

func (_c *MockApplier_Apply_Call) Run(run func(ctx context.Context, req compose.Request)) *MockApplier_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compose.Request
		if args[1] != nil {
			arg1 = args[1].(compose.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApplier_Apply_Call) Return(containers []compose.Container, err error) *MockApplier_Apply_Call {
	_c.Call.Return(containers, err)
	return _c
}

func (_c *MockApplier_Apply_Call) RunAndReturn(run func(ctx context.Context, req compose.Request) ([]compose.Container, error)) *MockApplier_Apply_Call {
	_c.Call.Return(run)
	return _c
}
