name: Generate SBOM
description: Generate SBOM for a Docker image using anchore/sbom-action

inputs:
  image:
    description: "Image to scan"
    required: true
  output-file:
    description: "Output file path"
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        image: ${{ inputs.image }}
        format: spdx-json
        output-file: ${{ inputs.output-file }}
