package notifications

import (
	"encoding/json"
	"maps"
	"os"
	"reflect"
	"slices"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/nicholas-fedor/watchtower/pkg/types"
)

// Paths of the template-preview module's generated lists of the container
// report contract, relative to this package.
const (
	tplprevReportMethodsPath = "../../tools/tplprev/internal/report/testdata/container-report-methods.txt"
	tplprevJSONKeysPath      = "../../tools/tplprev/internal/notify/testdata/container-json-keys.txt"
)

// tplprevContractHeader starts each generated contract list.
const tplprevContractHeader = "# Generated by TestTplprevReportContractInSync in pkg/notifications. DO NOT EDIT.\n"

// containerReportMethods returns the sorted method names templates can call
// on a container report.
func containerReportMethods() []string {
	reportType := reflect.TypeFor[types.ContainerReport]()

	names := make([]string, 0, reportType.NumMethod())
	for method := range reportType.Methods() {
		names = append(names, method.Name)
	}

	slices.Sort(names)

	return names
}

// containerJSONKeys returns the sorted keys the JSON output can carry for a
// container, collected from a report whose containers set every field.
func containerJSONKeys(t *testing.T) []string {
	t.Helper()

	encoded, err := json.Marshal(Data{Report: goldenFullReport()})
	require.NoError(t, err)

	var decoded struct {
		Report map[string][]map[string]any `json:"report"`
	}
	require.NoError(t, json.Unmarshal(encoded, &decoded))

	keys := map[string]struct{}{}

	for _, containers := range decoded.Report {
		for _, container := range containers {
			for key := range container {
				keys[key] = struct{}{}
			}
		}
	}

	return slices.Sorted(maps.Keys(keys))
}

// contractList returns lines as a generated contract list.
func contractList(lines []string) []byte {
	return []byte(tplprevContractHeader + strings.Join(lines, "\n") + "\n")
}

// TestTplprevReportContractInSync fails when the template-preview module's
// lists of container report methods and container JSON keys differ from what
// notifications provide. The preview module's own tests check its report type
// and JSON output against these lists. Set UPDATE_GOLDEN=1 to regenerate them.
func TestTplprevReportContractInSync(t *testing.T) {
	lists := map[string][]byte{
		tplprevReportMethodsPath: contractList(containerReportMethods()),
		tplprevJSONKeysPath:      contractList(containerJSONKeys(t)),
	}

	for path, want := range lists {
		if os.Getenv("UPDATE_GOLDEN") == "1" {
			require.NoError(t, os.WriteFile(path, want, 0o644))

			continue
		}

		got, err := os.ReadFile(path)
		require.NoError(t, err)

		assert.Equal(t, string(want), string(got), "%s is stale; run 'task tplprev:gen' and commit the result", path)
	}
}
