package notifications

import (
	"bytes"
	"fmt"
	"go/format"
	"maps"
	"os"
	"slices"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// tplprevTemplatesPath is the template-preview module's generated copy of the
// built-in templates, relative to this package.
const tplprevTemplatesPath = "../../tools/tplprev/internal/templates/templates_gen.go"

// generateTplprevTemplates returns the Go source of the template-preview
// module's copy of the built-in templates. The preview module cannot import
// this one, so it keeps a generated copy instead.
func generateTplprevTemplates(t *testing.T) []byte {
	t.Helper()

	var src bytes.Buffer

	src.WriteString("// Code generated by TestTplprevTemplatesInSync in pkg/notifications. DO NOT EDIT.\n\n")
	src.WriteString("package templates\n\n")
	src.WriteString("// Templates is a snapshot of Watchtower's named notification templates.\n")
	src.WriteString("var Templates = map[string]string{\n")

	for _, name := range slices.Sorted(maps.Keys(commonTemplates)) {
		fmt.Fprintf(&src, "%s: %s,\n", strconv.Quote(name), goStringLiteral(commonTemplates[name]))
	}

	src.WriteString("}\n")

	formatted, err := format.Source(src.Bytes())
	require.NoError(t, err)

	return formatted
}

// goStringLiteral returns s as a raw string literal when it can be one, so the
// generated templates stay readable, and as a quoted literal otherwise.
func goStringLiteral(s string) string {
	if strings.Contains(s, "`") || strings.Contains(s, "\r") {
		return strconv.Quote(s)
	}

	return "`" + s + "`"
}

// TestTplprevTemplatesInSync fails when the template-preview module's copy of
// the built-in templates differs from the templates notifications use. Set
// UPDATE_GOLDEN=1 to regenerate the copy.
func TestTplprevTemplatesInSync(t *testing.T) {
	want := generateTplprevTemplates(t)

	if os.Getenv("UPDATE_GOLDEN") == "1" {
		require.NoError(t, os.WriteFile(tplprevTemplatesPath, want, 0o644))

		return
	}

	got, err := os.ReadFile(tplprevTemplatesPath)
	require.NoError(t, err)

	assert.Equal(t, string(want), string(got),
		"%s is stale; run 'task tplprev:gen' and commit the result", tplprevTemplatesPath)
}
