name: Cache cleanup
on:
  workflow_dispatch: {}
  pull_request:
    types:
      - closed

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          echo "Fetching list of cache keys"
          gh cache list --ref "$BRANCH" --limit 100 --json id --jq '.[].id' | while IFS= read -r cacheKey; do
            ## Setting this to not fail the workflow while deleting cache keys.
            set +e
            echo "Deleting cache: $cacheKey"
            gh cache delete "$cacheKey"
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
