name: Publish Docs

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Release (Production)"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  actions: read

env:
  GO_VERSION: 1.24.x

jobs:
  publish-docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build tplprev
        run: scripts/build-tplprev.sh
      - name: Setup python
        uses: actions/setup-python@19e4675e06535f6b54e894da5c1f044400bb4996
        with:
          python-version: "3.13.2"
          cache: "pip"
          cache-dependency-path: |
            docs-requirements.txt
      - name: Install mkdocs
        run: |
          pip install -r docs-requirements.txt
      - name: Generate docs
        run: mkdocs gh-deploy --strict
