name: Pull Request

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  GO_VERSION: 1.24.x

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@dec74fa03096ff515422f71d18d41307cacde373

  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.24.x # Hardcode here or use a separate job to set matrix values
        platform:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: |
          go test -v -coverprofile coverage.out -covermode atomic ./...
      - name: Publish coverage
        uses: codecov/codecov-action@ea99328d1c4d5f39fda7cbffe104afd6906c50b0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3
        with:
          version: v2.7.0
          args: --snapshot --verbose
