name: Pull Request

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - cmd
      - internal
      - pkg
      - go.mod
      - go.sum
      - main.go

permissions:
  contents: read

jobs:
  Lint:
    uses: ./.github/workflows/lint.yaml

  Test:
    uses: ./.github/workflows/test.yaml
