---
name: Run Security Checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - cmd/**
      - pkg/**
      - internal/**
      - main.go
      - go.mod
      - go.sum
  schedule:
    - cron: "0 0 * * *"

env:
  OUTPUT_FILE: results.sarif

permissions:
  contents: read # Set default read-only permissions

jobs:
  gosec:
    name: Run gosec Scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Harden the Runner (Step Security)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run Gosec Security Scanner
        uses: securego/gosec@4a3bd8af174872c778439083ded7adbf3747e770 # v2.26.1
        with:
          args: "-exclude-generated -no-fail -fmt sarif -out ${{ env.OUTPUT_FILE }} ./..."

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        with:
          sarif_file: ${{ env.OUTPUT_FILE }}
          category: gosec-sarif

  govulncheck:
    name: Run govulncheck Scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Harden the Runner (Step Security)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Run govulncheck
        id: govulncheck
        uses: nicholas-fedor/govulncheck-action@ec1863b9cabfebf9821a767490e935e70dd18af8 # v1.0.4
        with:
          output-format: sarif
          output-file: ${{ env.OUTPUT_FILE }}
          go-version-file: "go.mod"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        with:
          sarif_file: ${{ env.OUTPUT_FILE }}
          category: govulncheck-sarif
