name: Run tests and upload coverage

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: "**/go.sum"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: |
          go test -race -p 1 -coverprofile="coverage.out" ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
