---
name: Refresh pkg.go.dev

on:
  - workflow_dispatch
  - workflow_call

permissions:
  contents: read # Set default read-only permissions

jobs:
  update-go-docs:
    name: Update pkg.go.dev
    runs-on: ubuntu-latest
    steps:
      - name: Harden the Runner (Step Security)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Run pkg.go.dev Update
        uses: nicholas-fedor/go-proxy-pull-action@1214c22a1ec7c778f1f023f6918621d64f3ba1de # v1.1.9
        with:
          goproxy: https://proxy.golang.org
          import_path: github.com/nicholas-fedor/watchtower
