---
name: Refresh pkg.go.dev

on:
  - workflow_dispatch
  - workflow_call

permissions:
  contents: read # Set default read-only permissions

jobs:
  update-go-docs:
    name: Update pkg.go.dev
    runs-on: ubuntu-latest
    steps:
      - name: Harden the Runner (Step Security)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Run pkg.go.dev Update
        uses: nicholas-fedor/go-proxy-pull-action@23667e1e5ec1ed9f0aaa55441d97981f8607e1d7 # v1.1.13
        with:
          goproxy: https://proxy.golang.org
          import_path: github.com/nicholas-fedor/watchtower
