---
name: Refresh pkg.go.dev

on:
  - workflow_dispatch
  - workflow_call

permissions:
  contents: read # Set default read-only permissions

jobs:
  update-go-docs:
    name: Update pkg.go.dev
    runs-on: ubuntu-latest
    steps:
      - name: Harden the Runner (Step Security)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Run pkg.go.dev Update
        uses: nicholas-fedor/go-proxy-pull-action@68464ba608c471bf13d8d839deb044334070a52a # v1.1.25
        with:
          goproxy: https://proxy.golang.org
          import_path: github.com/nicholas-fedor/watchtower
