// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/watchtower/pkg/types"
	"github.com/rs/zerolog"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFetcher creates a new instance of MockFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockFetcher is an autogenerated mock type for the Fetcher type
type MockFetcher struct {
	mock.Mock
}

type MockFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcher) EXPECT() *MockFetcher_Expecter {
	return &MockFetcher_Expecter{mock: &_m.Mock}
}

// FetchDigestForTag provides a mock function for the type MockFetcher
func (_mock *MockFetcher) FetchDigestForTag(log *zerolog.Logger, ctx context.Context, container types.Container, authToken string, tag string, endpoints ...string) (string, error) {
	var tmpRet mock.Arguments
	if len(endpoints) > 0 {
		tmpRet = _mock.Called(log, ctx, container, authToken, tag, endpoints)
	} else {
		tmpRet = _mock.Called(log, ctx, container, authToken, tag)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FetchDigestForTag")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*zerolog.Logger, context.Context, types.Container, string, string, ...string) (string, error)); ok {
		return returnFunc(log, ctx, container, authToken, tag, endpoints...)
	}
	if returnFunc, ok := ret.Get(0).(func(*zerolog.Logger, context.Context, types.Container, string, string, ...string) string); ok {
		r0 = returnFunc(log, ctx, container, authToken, tag, endpoints...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*zerolog.Logger, context.Context, types.Container, string, string, ...string) error); ok {
		r1 = returnFunc(log, ctx, container, authToken, tag, endpoints...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcher_FetchDigestForTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchDigestForTag'
type MockFetcher_FetchDigestForTag_Call struct {
	*mock.Call
}

// FetchDigestForTag is a helper method to define mock.On call
//   - log *zerolog.Logger
//   - ctx context.Context
//   - container types.Container
//   - authToken string
//   - tag string
//   - endpoints ...string
func (_e *MockFetcher_Expecter) FetchDigestForTag(log any, ctx any, container any, authToken any, tag any, endpoints ...any) *MockFetcher_FetchDigestForTag_Call {
	return &MockFetcher_FetchDigestForTag_Call{Call: _e.mock.On("FetchDigestForTag",
		append([]any{log, ctx, container, authToken, tag}, endpoints...)...)}
}

func (_c *MockFetcher_FetchDigestForTag_Call) Run(run func(log *zerolog.Logger, ctx context.Context, container types.Container, authToken string, tag string, endpoints ...string)) *MockFetcher_FetchDigestForTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *zerolog.Logger
		if args[0] != nil {
			arg0 = args[0].(*zerolog.Logger)
		}
		var arg1 context.Context
		if args[1] != nil {
			arg1 = args[1].(context.Context)
		}
		var arg2 types.Container
		if args[2] != nil {
			arg2 = args[2].(types.Container)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []string
		var variadicArgs []string
		if len(args) > 5 {
			variadicArgs = args[5].([]string)
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *MockFetcher_FetchDigestForTag_Call) Return(s string, err error) *MockFetcher_FetchDigestForTag_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFetcher_FetchDigestForTag_Call) RunAndReturn(run func(log *zerolog.Logger, ctx context.Context, container types.Container, authToken string, tag string, endpoints ...string) (string, error)) *MockFetcher_FetchDigestForTag_Call {
	_c.Call.Return(run)
	return _c
}
